#Crear una cuenta en el sandbox
#https://www.sandbox.paypal.com/us/welcome/signup/#/country_selection
#Crear una tarjeta simulada
#https://developer.paypal.com/api/rest/sandbox/card-testing/
#Crear credenciales para el sandbox
#https://developer.paypal.com/dashboard/applications/sandbox
paypal.client-id=AfpH-_2uVMjohyvWzuPn9QX0olYNKt5DX3ap52s7m3s6_3slGPn7mpqchtK77EJv4bisAwBViQpT3ew8
paypal.client-secret=EMdvtLFxD77h-lFNBydBhiFKWxknKvywyFEhTxUCz2ANEClOvmCYu1GJF8BBeiZ6UK_FvBlO1JrcobW-
# 'sandbox' para modo testeo y 'live' para produccion
paypal.mode=sandbox

